In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Loading data

In [24]:
circuits = pd.read_csv('data/circuits.csv')
constructor_results = pd.read_csv('data/constructor_results.csv')
constructor_standings = pd.read_csv('data/constructor_standings.csv')
constructors = pd.read_csv('data/constructors.csv')
driver_standings = pd.read_csv('data/driver_standings.csv')
drivers = pd.read_csv('data/drivers.csv')
lap_times = pd.read_csv('data/lap_times.csv')
pit_stops = pd.read_csv('data/pit_stops.csv')
qualifying = pd.read_csv('data/qualifying.csv')
races = pd.read_csv('data/races.csv')
results = pd.read_csv('data/results.csv')
seasons = pd.read_csv('data/seasons.csv')
sprint_results = pd.read_csv('data/sprint_results.csv')
status = pd.read_csv('data/status.csv')

# Understanding, refining and cleaning data

In [25]:
races = races[races['year'] >= 2020]

In [5]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
1018,1031,2020,1,70,Austrian Grand Prix,2020-07-05,13:10:00,http://en.wikipedia.org/wiki/2020_Austrian_Gra...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1019,1032,2020,2,70,Styrian Grand Prix,2020-07-12,13:10:00,http://en.wikipedia.org/wiki/2020_Styrian_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1020,1033,2020,3,11,Hungarian Grand Prix,2020-07-19,13:10:00,http://en.wikipedia.org/wiki/2020_Hungarian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1021,1034,2020,4,9,British Grand Prix,2020-08-02,13:10:00,http://en.wikipedia.org/wiki/2020_British_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1022,1035,2020,5,9,70th Anniversary Grand Prix,2020-08-09,13:10:00,http://en.wikipedia.org/wiki/70th_Anniversary_...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [26]:
cols = ['raceId', 'circuitId', 'year', 'round', 'name', 'date', 'time']
df = races[cols]

In [9]:
print(df.shape)

(107, 7)

In [33]:
df.dtypes

raceId                      int64
circuitId                   int64
year                        int64
round                       int64
name                       object
date                       object
time                       object
qualifyId                   int64
driverId                    int64
constructorId               int64
number                      int64
q1                         object
q2                         object
q3                         object
grid                        int64
driverStandingsId           int64
points_x                  float64
position_x                  int64
positionText_x             object
wins_x                      int64
constructorStandingsId      int64
points_y                  float64
position_y                  int64
positionText_y             object
wins_y                      int64
dtype: object

In [10]:
qualifying.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [27]:
df = df.merge(qualifying, on='raceId', how='left')

In [28]:
df['grid'] = df['position']
df = df.drop(columns='position')

In [13]:
print(df.shape)
df.head()

(2138, 15)

,raceId,circuitId,year,round,name,date,time,qualifyId,driverId,constructorId,number,q1,q2,q3,grid
0,1031,70,2020,1,Austrian Grand Prix,2020-07-05,13:10:00,8378,822,131,77,1:04.111,1:03.015,1:02.939,1
1,1031,70,2020,1,Austrian Grand Prix,2020-07-05,13:10:00,8379,1,131,44,1:04.198,1:03.096,1:02.951,2
2,1031,70,2020,1,Austrian Grand Prix,2020-07-05,13:10:00,8380,830,9,33,1:04.024,1:04.000,1:03.477,3
3,1031,70,2020,1,Austrian Grand Prix,2020-07-05,13:10:00,8381,846,1,4,1:04.606,1:03.819,1:03.626,4
4,1031,70,2020,1,Austrian Grand Prix,2020-07-05,13:10:00,8382,848,9,23,1:04.661,1:03.746,1:03.868,5

1031 is the first race in dataset that we are observing.

In [29]:
driver_standings = driver_standings[driver_standings['raceId'] >= 1031]
constructor_standings = constructor_standings[constructor_standings['raceId'] >= 1031]

In [15]:
driver_standings.head()

,driverStandingsId,raceId,driverId,points,position,positionText,wins
32566,69888,1034,830,52.0,3,3,0
32567,69887,1034,817,20.0,9,9,0
32568,69886,1034,840,20.0,8,8,0
32569,69885,1034,825,1.0,16,16,0
32570,69884,1034,154,0.0,20,20,0

In [16]:
constructor_standings.head()

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins
12316,27522,1034,210,1.0,9,9,0
12317,27521,1034,9,78.0,2,2,0
12318,27520,1034,3,0.0,10,10,0
12319,27519,1034,51,2.0,8,8,0
12320,27518,1034,4,32.0,6,6,0

In [30]:
print('Driver standings shape: ', driver_standings.shape)
print('Constructor standings shape: ', constructor_standings.shape)

Driver standings shape:  (2256, 7)
Constructor standings shape:  (1070, 7)

In [31]:
df = df.merge(driver_standings, on=['raceId', 'driverId'], how='left')
df = df.merge(constructor_standings, on=['raceId', 'constructorId'], how='left')

In [32]:
df.shape

(2138, 25)

# Model 1?

### Libraries

In [19]:
from sklearn.pipeline import Pipeline

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import FunctionTransformer
from sklearn.base import clone

### Creating classes that will generate new features

In [35]:
class DriverStandings(BaseEstimator, TransformerMixin):
    def __init__(
        self, 
        race_col='raceId', 
        driver_col='driverId', 
        season_col='year',
        round_col='round',
        points_col='points', 
        position_col='position', 
        wins_col='wins'
    ):
        self.race_col=race_col
        self.driver_col=driver_col
        self.season_col=season_col
        self.round_col=round_col
        self.points_col=points_col
        self.position_col=position_col
        self.wins_col=wins_col

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        df = X.copy()

        df = df.sort_values(by=[self.driver_col, self.season_col, self.round_col])
        group_cols = [self.driver_col, self.season_col]
        
        df['before_race_points'] = df.groupby(group_cols)[self.points_col].shift(1)
        df['before_race_position'] = df.groupby(group_cols)[self.position_col].shift(1)
        df['before_race_wins'] = df.groupby(group_cols)[self.wins_col].shift(1)

        df.loc[df[self.round_col] == 1, [
            'before_race_points',
            'before_race_position',
            'before_race_wins'
        ]] = 0

        # if missing values
        df[['before_race_points', 'before_race_position', 'before_race_wins']] = \
            df[['before_race_points', 'before_race_position', 'before_race_wins']].fillna(0)

        return df

In [38]:
class ConstructorStandings(BaseEstimator, TransformerMixin):
    def __init__(
        self, 
        race_col='raceId', 
        constructor_col='constructorId', 
        season_col='year',
        round_col='round',
        points_col='points', 
        position_col='position', 
        wins_col='wins'
    ):
        self.race_col=race_col
        self.constructor_col=constructor_col
        self.season_col=season_col
        self.round_col=round_col
        self.points_col=points_col
        self.position_col=position_col
        self.wins_col=wins_col

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        df = X.copy()

        df = df.sort_values(by=[self.constructor_col, self.season_col, self.round_col, self.race_col])
        group_cols = [self.constructor_col, self.season_col]

        df['cumulative_points'] = (
            df.groupby(group_cols)[self.points_col].cumsum()
        )
        
        df['before_race_ctor_points'] = df.groupby(group_cols)['cumulative_points'].shift(1).fillna(0)
        df['before_race_ctor_position'] = df.groupby(group_cols)[self.position_col].shift(1).fillna(0)
        df['before_race_ctor_wins'] = df.groupby(group_cols)[self.wins_col].shift(1).fillna(0)

        df.loc[df[self.round_col] == 1, [
            'before_race_ctor_points',
            'before_race_ctor_position',
            'before_race_ctor_wins'
        ]] = 0

        return df